fix again branch bis

diff --git a/.github/workflows/monitoring-metrics.yml b/.github/workflows/monitoring-metrics.yml
--- a/.github/workflows/monitoring-metrics.yml
+++ b/.github/workflows/monitoring-metrics.yml
@@ -6,7 +6,6 @@ on:
       - "main"
     paths:
       - 'src/outputs-baseline-prod/*.db'
-      - 'src/outputs-baseline-prod/*.db'
       
   workflow_dispatch:
 
@@ -15,128 +14,128 @@ permissions:
 
 jobs:
   render-charts:
-      runs-on: ubuntu-latest
+    runs-on: ubuntu-latest
     
-  steps:
-    # 1. Scarica il codice del repository
-    - name: Checkout repository
-      uses: actions/checkout@v4
+    steps:
+      # 1. Scarica il codice del repository
+      - name: Checkout repository
+        uses: actions/checkout@v4
 
-    # 2. Configura i permessi ed esegui lo script del DB
-    - name: Esegui install_db.sh
-      run: |
-        chmod +x ./install_db.sh
-        sudo ./install_db.sh src/outputs-baseline-prod/metrics_prod.db
-        sudo chmod -R 777 /opt/machineinnovation/
+      # 2. Configura i permessi ed esegui lo script del DB
+      - name: Esegui install_db.sh
+        run: |
+          chmod +x ./install_db.sh
+          sudo ./install_db.sh src/outputs-baseline-prod/metrics_prod.db
+          sudo chmod -R 777 /opt/machineinnovation/
 
-    # 3. Avvia Grafana
-    - name: Avvia Grafana
-      working-directory: ./monitoring
-      run: docker compose up -d grafana
+      # 3. Avvia Grafana
+      - name: Avvia Grafana
+        working-directory: ./monitoring
+        run: docker compose up -d grafana
 
-    # - name: Docker ps
-    #   run: docker ps -a
+      # - name: Docker ps
+      #   run: docker ps -a
 
-    # - name: Docker logs before
-    #   run: docker logs grafana || true
+      # - name: Docker logs before
+      #   run: docker logs grafana || true
 
-    # - name: Grafana curl before
-    #   run: curl -v http://localhost:3000/api/health || true
+      # - name: Grafana curl before
+      #   run: curl -v http://localhost:3000/api/health || true
 
-    # 4. Attendi che Grafana sia pronto stabilmente
-    - name: Wait start
-      run: sleep 60
+      # 4. Attendi che Grafana sia pronto stabilmente
+      - name: Wait start
+        run: sleep 60
     
-    # - name: Docker logs after
-    #   run: docker logs grafana || true
+      # - name: Docker logs after
+      #   run: docker logs grafana || true
 
-    # - name: Grafana curl after
-    #   run: curl -v http://localhost:3000/api/health || true
+      # - name: Grafana curl after
+      #   run: curl -v http://localhost:3000/api/health || true
 
-    - name: Wait Grafana Loop
-      run: |
-        MAX_RETRY=30
-        RETRY=0
+      - name: Wait Grafana Loop
+        run: |
+          MAX_RETRY=30
+          RETRY=0
 
-        until curl -s http://localhost:3000/api/health | grep -q '"database": "ok"'
-        do
-          RETRY=$((RETRY+1))
+          until curl -s http://localhost:3000/api/health | grep -q '"database": "ok"'
+          do
+            RETRY=$((RETRY+1))
 
-          echo "Tentativo ${RETRY}/${MAX_RETRY}: Grafana non pronta"
+            echo "Tentativo ${RETRY}/${MAX_RETRY}: Grafana non pronta"
 
-          if [ $RETRY -ge $MAX_RETRY ]; then
-            echo "ERRORE: timeout attesa Grafana"
-            exit 1
-          fi
+            if [ $RETRY -ge $MAX_RETRY ]; then
+              echo "ERRORE: timeout attesa Grafana"
+              exit 1
+            fi
 
-          sleep 5
-        done
+            sleep 5
+          done
 
-        echo "Grafana pronta"
+          echo "Grafana pronta"
 
-    # 5. controlla install plugin
-    # - name: Check plugin directory
-    #   run: |
-    #     docker exec grafana ls -la /var/lib/grafana/plugins || true
+      # 5. controlla install plugin
+      # - name: Check plugin directory
+      #   run: |
+      #     docker exec grafana ls -la /var/lib/grafana/plugins || true
 
-    # 6. Configura l'ambiente Python
-    - name: Set up Python
-      uses: actions/setup-python@v5
-      with:
-        python-version: '3.12' 
-        cache: 'pip'
+      # 6. Configura l'ambiente Python
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.12' 
+          cache: 'pip'
 
-    # 7. Installa Playwright e Chromium
-    - name: Installa dipendenze e Playwright
-      run: |
-        pip install playwright 
-        playwright install chromium --with-deps
+      # 7. Installa Playwright e Chromium
+      - name: Installa dipendenze e Playwright
+        run: |
+          pip install playwright 
+          playwright install chromium --with-deps
 
-    # 8 debug prima del python
-    # - name: Debug Grafana
-    #   run: |
-    #     curl http://localhost:3000/api/health
+      # 8 debug prima del python
+      # - name: Debug Grafana
+      #   run: |
+      #     curl http://localhost:3000/api/health
     
-    # - name: List dashboards
-    #   run: |
-    #     curl -u admin:admin \
-    #     http://localhost:3000/api/search
+      # - name: List dashboards
+      #   run: |
+      #     curl -u admin:admin \
+      #     http://localhost:3000/api/search
     
-    # - name: List datasources
-    #   run: |
-    #     curl -u admin:admin \
-    #     http://localhost:3000/api/datasources
+      # - name: List datasources
+      #   run: |
+      #     curl -u admin:admin \
+      #     http://localhost:3000/api/datasources
 
-    # 9. Rimuove le vecchie immagini e cattura i nuovi Screenshot
-    - name: Catch Screenshot Dashboard
-      run: |
-        rm -f ./images/dashboard_table.png
-        rm -f ./images/dashboard_timeseries.png
-        python ./monitoring/rend_dashboard_panel.py
+      # 9. Rimuove le vecchie immagini e cattura i nuovi Screenshot
+      - name: Catch Screenshot Dashboard
+        run: |
+          rm -f ./images/dashboard_table.png
+          rm -f ./images/dashboard_timeseries.png
+          python ./monitoring/rend_dashboard_panel.py
         
-    # 10. [DEBUG] Verifica i percorsi di output
-    - name: Debug Images check
-      run: |
-        echo "=== Contenuto della Root ==?"
-        ls -lrt
-        echo "=== Contenuto di ./images/ ==="
-        ls -lrt ./images/ || true
-        echo "=== Contenuto di ./monitoring/ ==="
-        ls -lrt ./monitoring/ || true
+      # 10. [DEBUG] Verifica i percorsi di output
+      - name: Debug Images check
+        run: |
+          echo "=== Contenuto della Root ==?"
+          ls -lrt
+          echo "=== Contenuto di ./images/ ==="
+          ls -lrt ./images/ || true
+          echo "=== Contenuto di ./monitoring/ ==="
+          ls -lrt ./monitoring/ || true
         
-    - name: Test query on db
-      run: |
-        sqlite3 /opt/machineinnovation/db/metrics.db "
-        SELECT *
-        FROM model_metrics_baseline; "
+      - name: Test query on db
+        run: |
+          sqlite3 /opt/machineinnovation/db/metrics.db "
+          SELECT *
+          FROM model_metrics_baseline; "
 
-    # 11. Spegni i container Docker 
-    - name: Stop Docker
-      working-directory: ./monitoring
-      run: docker compose down
+      # 11. Spegni i container Docker 
+      - name: Stop Docker
+        working-directory: ./monitoring
+        run: docker compose down
 
-    # 12. Commit e Push sul repository
-    - name: Commit + Push of the update graph 
+      # 12. Commit e Push sul repository
+      - name: Commit + Push of the update graph 
       run: |
         git config --local user.name "francescofrigerio"
         git config --local user.email "francesco.frigerio@greencore.it"
@@ -148,8 +147,8 @@ jobs:
         # per evitare salvataggi inutili e sistematici
         # esegue il seguente controllo
         if git diff --cached --quiet; then
-           echo "Nessuna modifica alle immagini"
-           exit 0
+             echo "Nessuna modifica alle immagini"
+             exit 0
         fi
 
         git commit -m "Auto: Aggiornato grafico di training [skip ci]" || exit 0
