add fix wait retry check to avoid commit and push

diff --git a/.github/workflows/update-graphs.yml b/.github/workflows/update-graphs.yml
--- a/.github/workflows/update-graphs.yml
+++ b/.github/workflows/update-graphs.yml
@@ -32,30 +32,71 @@ jobs:
       run: docker compose up -d grafana
 
     # 4. Attendi che Grafana sia pronto stabilmente
-    - name: Wait start
-      run: sleep 60
+    # - name: Wait start
+    #   run: sleep 60
+    - name: Wait Grafana
+    
+      run: |
+        MAX_RETRY=30
+        RETRY=0
 
-    # 5. Configura l'ambiente Python
+        until curl -s http://localhost:3000/api/health | grep -q "\"database\":\"ok\""
+        do
+          RETRY=$((RETRY+1))
+
+          echo "Tentativo ${RETRY}/${MAX_RETRY}: Grafana non pronta"
+
+          if [ $RETRY -ge $MAX_RETRY ]; then
+            echo "ERRORE: timeout attesa Grafana"
+            exit 1
+          fi
+
+          sleep 5
+        done
+
+        echo "Grafana pronta"
+
+    # 5. controlla install plugin
+    - name: Check plugin directory
+      run: |
+        docker exec grafana ls -la /var/lib/grafana/plugins || true
+
+    # 6. Configura l'ambiente Python
     - name: Set up Python
       uses: actions/setup-python@v5
       with:
         python-version: '3.12' 
         cache: 'pip'
 
-    # 6. Installa Playwright e Chromium
+    # 7. Installa Playwright e Chromium
     - name: Installa dipendenze e Playwright
       run: |
         pip install playwright 
         playwright install chromium --with-deps
 
-    # 7. Rimuove le vecchie immagini e cattura i nuovi Screenshot
+    # 8 debug prima del python
+    - name: Debug Grafana
+      run: |
+        curl http://localhost:3000/api/health
+    
+    - name: List dashboards
+      run: |
+        curl -u admin:admin \
+        http://localhost:3000/api/search
+    
+    - name: List datasources
+      run: |
+        curl -u admin:admin \
+        http://localhost:3000/api/datasources
+
+    # 9. Rimuove le vecchie immagini e cattura i nuovi Screenshot
     - name: Catch Screenshot Dashboard
       run: |
         rm -f ./images/dashboard_table.png
         rm -f ./images/dashboard_timeseries.png
         python ./monitoring/rend_dashboard_panel.py
         
-    # 8. [DEBUG] Verifica i percorsi di output
+    # 10. [DEBUG] Verifica i percorsi di output
     - name: Debug Images check
       run: |
         echo "=== Contenuto della Root ==?"
@@ -65,17 +106,29 @@ jobs:
         echo "=== Contenuto di ./monitoring/ ==="
         ls -lrt ./monitoring/ || true
         
-    # 9. Spegni i container Docker 
+    # 11. Spegni i container Docker 
     - name: Stop Docker
       working-directory: ./monitoring
       run: docker compose down
 
-    # 10. Commit e Push sul repository
+    # 12. Commit e Push sul repository
     - name: Commit + Push of the update graph 
       run: |
         git config --local user.name "francescofrigerio"
         git config --local user.email "francesco.frigerio@greencore.it"
         git add ./images/dashboard_table.png
         git add ./images/dashboard_timeseries.png
+
+        # le immagini png possono essere modificate 
+        # di poco ad ogni esecuzione
+        # per evitare salvataggi inutili e sistematici
+        # esegue il seguente controllo
+        if git diff --cached --quiet; then
+          echo "Nessuna modifica alle immagini"
+          exit 0
+        fi
+
         git commit -m "Auto: Aggiornato grafico di training [skip ci]" || exit 0
         git push
+        # dopo ogni commit automatico fare un git pull
+        # ad ogni partenza del codespace 
